/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MontadorRouteImport } from './routes/montador'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PoliticasDeCookiesRouteImport } from './routes/politicas-de-cookies'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminCidadesRouteImport } from './routes/admin.cidades'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminImportacoesRouteImport } from './routes/admin.importacoes'
import { Route as AdminLinksRouteImport } from './routes/admin.links'
import { Route as AdminMontadoresRouteImport } from './routes/admin.montadores'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminServicosRouteImport } from './routes/admin.servicos'
import { Route as AdminMontadoresIdRouteImport } from './routes/admin.montadores.$id'
import { Route as SServicoCidadeRouteImport } from './routes/s.$servico.$cidade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MontadorRoute = MontadorRouteImport.update({
  id: '/montador',
  path: '/montador',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticasDeCookiesRoute = PoliticasDeCookiesRouteImport.update({
  id: '/politicas-de-cookies',
  path: '/politicas-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCidadesRoute = AdminCidadesRouteImport.update({
  id: '/cidades',
  path: '/cidades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportacoesRoute = AdminImportacoesRouteImport.update({
  id: '/importacoes',
  path: '/importacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMontadoresRoute = AdminMontadoresRouteImport.update({
  id: '/montadores',
  path: '/montadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicosRoute = AdminServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMontadoresIdRoute = AdminMontadoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminMontadoresRoute,
} as any)
const SServicoCidadeRoute = SServicoCidadeRouteImport.update({
  id: '/s/$servico/$cidade',
  path: '/s/$servico/$cidade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/montador': typeof MontadorRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politicas-de-cookies': typeof PoliticasDeCookiesRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/importacoes': typeof AdminImportacoesRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/montadores': typeof AdminMontadoresRouteWithChildren
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/montadores/$id': typeof AdminMontadoresIdRoute
  '/s/$servico/$cidade': typeof SServicoCidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/montador': typeof MontadorRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politicas-de-cookies': typeof PoliticasDeCookiesRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/importacoes': typeof AdminImportacoesRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/montadores': typeof AdminMontadoresRouteWithChildren
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin': typeof AdminIndexRoute
  '/admin/montadores/$id': typeof AdminMontadoresIdRoute
  '/s/$servico/$cidade': typeof SServicoCidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/montador': typeof MontadorRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politicas-de-cookies': typeof PoliticasDeCookiesRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/importacoes': typeof AdminImportacoesRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/montadores': typeof AdminMontadoresRouteWithChildren
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/montadores/$id': typeof AdminMontadoresIdRoute
  '/s/$servico/$cidade': typeof SServicoCidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/montador'
    | '/politica-de-privacidade'
    | '/politicas-de-cookies'
    | '/termos-de-uso'
    | '/admin/auditoria'
    | '/admin/cidades'
    | '/admin/configuracoes'
    | '/admin/importacoes'
    | '/admin/links'
    | '/admin/montadores'
    | '/admin/relatorios'
    | '/admin/servicos'
    | '/admin/'
    | '/admin/montadores/$id'
    | '/s/$servico/$cidade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/montador'
    | '/politica-de-privacidade'
    | '/politicas-de-cookies'
    | '/termos-de-uso'
    | '/admin/auditoria'
    | '/admin/cidades'
    | '/admin/configuracoes'
    | '/admin/importacoes'
    | '/admin/links'
    | '/admin/montadores'
    | '/admin/relatorios'
    | '/admin/servicos'
    | '/admin'
    | '/admin/montadores/$id'
    | '/s/$servico/$cidade'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/montador'
    | '/politica-de-privacidade'
    | '/politicas-de-cookies'
    | '/termos-de-uso'
    | '/admin/auditoria'
    | '/admin/cidades'
    | '/admin/configuracoes'
    | '/admin/importacoes'
    | '/admin/links'
    | '/admin/montadores'
    | '/admin/relatorios'
    | '/admin/servicos'
    | '/admin/'
    | '/admin/montadores/$id'
    | '/s/$servico/$cidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MontadorRoute: typeof MontadorRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PoliticasDeCookiesRoute: typeof PoliticasDeCookiesRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  SServicoCidadeRoute: typeof SServicoCidadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montador': {
      id: '/montador'
      path: '/montador'
      fullPath: '/montador'
      preLoaderRoute: typeof MontadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicas-de-cookies': {
      id: '/politicas-de-cookies'
      path: '/politicas-de-cookies'
      fullPath: '/politicas-de-cookies'
      preLoaderRoute: typeof PoliticasDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cidades': {
      id: '/admin/cidades'
      path: '/cidades'
      fullPath: '/admin/cidades'
      preLoaderRoute: typeof AdminCidadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/importacoes': {
      id: '/admin/importacoes'
      path: '/importacoes'
      fullPath: '/admin/importacoes'
      preLoaderRoute: typeof AdminImportacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/montadores': {
      id: '/admin/montadores'
      path: '/montadores'
      fullPath: '/admin/montadores'
      preLoaderRoute: typeof AdminMontadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servicos': {
      id: '/admin/servicos'
      path: '/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AdminServicosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/montadores/$id': {
      id: '/admin/montadores/$id'
      path: '/$id'
      fullPath: '/admin/montadores/$id'
      preLoaderRoute: typeof AdminMontadoresIdRouteImport
      parentRoute: typeof AdminMontadoresRoute
    }
    '/s/$servico/$cidade': {
      id: '/s/$servico/$cidade'
      path: '/s/$servico/$cidade'
      fullPath: '/s/$servico/$cidade'
      preLoaderRoute: typeof SServicoCidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminMontadoresRouteChildren {
  AdminMontadoresIdRoute: typeof AdminMontadoresIdRoute
}

const AdminMontadoresRouteChildren: AdminMontadoresRouteChildren = {
  AdminMontadoresIdRoute: AdminMontadoresIdRoute,
}

const AdminMontadoresRouteWithChildren = AdminMontadoresRoute._addFileChildren(
  AdminMontadoresRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminCidadesRoute: typeof AdminCidadesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminImportacoesRoute: typeof AdminImportacoesRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminMontadoresRoute: typeof AdminMontadoresRouteWithChildren
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminServicosRoute: typeof AdminServicosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminCidadesRoute: AdminCidadesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminImportacoesRoute: AdminImportacoesRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminMontadoresRoute: AdminMontadoresRouteWithChildren,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminServicosRoute: AdminServicosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MontadorRoute: MontadorRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PoliticasDeCookiesRoute: PoliticasDeCookiesRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  SServicoCidadeRoute: SServicoCidadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
